version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.0"
ports: "80:80;4000:4000;4100:4100"

packages: [jekyll, ruby-jekyll-coffeescript, ruby-jekyll-optional-front-matter]

command:
  build:
    - sudo chmod 777 -R /var/www/html
    - sudo chmod 777 /opt/docs/kasimir-misc.js
    - composer update



  jekyll: |
    JEKYLL_LOG_LEVEL=info jekyll serve -s /opt/docs -d /var/www/html --drafts --livereload --port 4000 --livereload-port 4100 --host 0.0.0.0

  dev:
    - killall jekyll ||  echo "no job"
    - D:kick jekyll

  killall:
    killall jekyll
