title: KasimirJS
description: educational grade development tools
google_analytics:
show_downloads: true
url: https://stefan-caraton.de

# Make directory-style links
permalink: pretty

livereload: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: developer camp

plugins:
- jekyll-optional-front-matter
